# Generated by Django 2.0.5 on 2018-12-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_auto_20180524_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/img/user_avatar/default.png', upload_to='static/img/user_avatar'),
        ),
    ]
